In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv('../clean_dssp_csv/1i3n.csv')
df.head(10)

,DSSP,PDB,CHAIN,AA,SS,3H,4H,5H,BEND,CHIR,...,ON2I,ON2E,TCO,KAPPA,ALPHA,PHI,PSI,X-CA,Y-CA,Z-CA
0,1.0,2.0,A,A,C,?,?,?,?,?,...,79.0,-0.2,0.0,360.0,360.0,360.0,-1.4,-4.8,7.2,22.5
1,2.0,3.0,A,E,C,?,?,?,?,-,...,79.0,-0.2,-0.6809999999999999,360.0,-126.5,-88.8,145.6,-1.4,8.7,21.7
2,3.0,4.0,A,K,E,?,?,?,?,-,...,80.0,-0.9,-0.3,2.4,-131.5,-88.8,174.4,1.3,7.7,24.2
3,4.0,5.0,A,V,E,?,?,?,?,-,...,2.0,-0.4,-0.993,20.7,-141.5,-123.8,122.5,3.8,9.6,26.3
4,5.0,6.0,A,L,E,?,?,?,?,-,...,2.0,-0.5,-0.735,14.2,-164.6,-85.6,131.1,7.4,8.4,26.1
5,6.0,7.0,A,V,E,>,?,?,?,-,...,3.0,-0.8,-0.945,3.6,-159.8,-118.7,106.8,9.2,8.5,29.5
6,7.0,8.0,A,T,E,3,?,?,S,+,...,25.0,-0.2,-0.6509999999999999,79.5,12.3,-85.0,145.9,13.0,8.2,29.3
7,8.0,9.0,A,G,T,>,?,?,S,+,...,6.0,-0.4,0.792,83.3,153.9,62.7,25.1,14.9,7.1,32.4
8,9.0,10.0,A,G,T,<,?,?,?,+,...,23.0,-0.1,0.541,56.7,65.3,-66.2,-9.4,11.4,6.1,33.8
9,10.0,11.0,A,A,T,3,?,?,S,+,...,28.0,-0.2,0.578,88.6,88.7,-89.4,-9.4,12.8,3.4,36.1

In [3]:
data = df[['AA', 'SS']]
data.head(10)

  AA SS
0  A  C
1  E  C
2  K  E
3  V  E
4  L  E
5  V  E
6  T  E
7  G  T
8  G  T
9  A  T

In [9]:
seq = data['AA'].values
seq

array(['A', 'E', 'K', 'V', 'L', 'V', 'T', 'G', 'G', 'A', 'G', 'Y', 'I',
       'G', 'S', 'H', 'T', 'V', 'L', 'E', 'L', 'L', 'E', 'A', 'G', 'Y',
       'L', 'P', 'V', 'V', 'I', 'D', 'N', 'F', 'H', 'N', 'A', 'F', 'R',
       'G', 'G', 'G', 'S', 'L', 'P', 'E', 'S', 'L', 'R', 'R', 'V', 'Q',
       'E', 'L', 'T', 'G', 'R', 'S', 'V', 'E', 'F', 'E', 'E', 'M', 'D',
       'I', 'L', 'D', 'Q', 'G', 'A', 'L', 'Q', 'R', 'L', 'F', 'K', 'K',
       'Y', 'S', 'F', 'M', 'A', 'V', 'I', 'H', 'F', 'A', 'G', 'L', 'K',
       'A', 'M', 'G', 'E', 'S', 'V', 'Q', 'K', 'P', 'L', 'D', 'Y', 'Y',
       'R', 'V', 'N', 'L', 'T', 'G', 'T', 'I', 'Q', 'L', 'L', 'E', 'I',
       'M', 'K', 'A', 'H', 'G', 'V', 'K', 'N', 'L', 'V', 'F', 'S', 'S',
       'S', 'A', 'T', 'V', 'Y', 'G', 'N', 'P', 'Q', 'Y', 'L', 'P', 'L',
       'D', 'E', 'A', 'H', 'P', 'T', 'G', 'G', 'C', 'T', 'N', 'P', 'Y',
       'G', 'K', 'S', 'K', 'F', 'F', 'I', 'E', 'E', 'M', 'I', 'R', 'D',
       'L', 'C', 'Q', 'A', 'D', 'K', 'T', 'W', 'N', 'V', 'V', 'L', 'L',
       'R', 'Y', 'F', 'N', 'P', 'T', 'G', 'A', 'H', 'A', 'S', 'G', 'C',
       'I', 'G', 'E', 'D', 'P', 'Q', 'G', 'I', 'P', 'N', 'N', 'L', 'M',
       'P', 'Y', 'V', 'S', 'Q', 'V', 'A', 'I', 'G', 'R', 'R', 'E', 'A',
       'L', 'N', 'V', 'F', 'G', 'N', 'D', 'Y', 'D', 'T', 'E', 'D', 'G',
       'T', 'G', 'V', 'R', 'D', 'Y', 'I', 'H', 'V', 'V', 'D', 'L', 'A',
       'K', 'G', 'H', 'I', 'A', 'A', 'L', 'R', 'K', 'L', 'K', 'E', 'Q',
       'C', 'G', 'C', 'R', 'I', 'Y', 'N', 'L', 'G', 'T', 'G', 'T', 'G',
       'Y', 'S', 'V', 'L', 'Q', 'M', 'V', 'Q', 'A', 'M', 'E', 'K', 'A',
       'S', 'G', 'K', 'K', 'I', 'P', 'Y', 'K', 'V', 'V', 'A', 'R', 'R',
       'E', 'G', 'D', 'V', 'A', 'A', 'C', 'Y', 'A', 'N', 'P', 'S', 'L',
       'A', 'Q', 'E', 'E', 'L', 'G', 'W', 'T', 'A', 'A', 'L', 'G', 'L',
       'D', 'R', 'M', 'C', 'E', 'D', 'L', 'W', 'R', 'W', 'Q', 'K', 'Q',
       'N', 'P', 'S', 'G', 'F', 'G', 'T', 'Q', 'A', 'A', 'E', 'K', 'V',
       'L', 'V', 'T', 'G', 'G', 'A', 'G', 'Y', 'I', 'G', 'S', 'H', 'T',
       'V', 'L', 'E', 'L', 'L', 'E', 'A', 'G', 'Y', 'L', 'P', 'V', 'V',
       'I', 'D', 'N', 'F', 'H', 'N', 'A', 'F', 'R', 'G', 'G', 'G', 'S',
       'L', 'P', 'E', 'S', 'L', 'R', 'R', 'V', 'Q', 'E', 'L', 'T', 'G',
       'R', 'S', 'V', 'E', 'F', 'E', 'E', 'M', 'D', 'I', 'L', 'D', 'Q',
       'G', 'A', 'L', 'Q', 'R', 'L', 'F', 'K', 'K', 'Y', 'S', 'F', 'M',
       'A', 'V', 'I', 'H', 'F', 'A', 'G', 'L', 'K', 'A', 'M', 'G', 'E',
       'S', 'V', 'Q', 'K', 'P', 'L', 'D', 'Y', 'Y', 'R', 'V', 'N', 'L',
       'T', 'G', 'T', 'I', 'Q', 'L', 'L', 'E', 'I', 'M', 'K', 'A', 'H',
       'G', 'V', 'K', 'N', 'L', 'V', 'F', 'S', 'S', 'S', 'A', 'T', 'V',
       'Y', 'G', 'N', 'P', 'Q', 'Y', 'L', 'P', 'L', 'D', 'E', 'A', 'H',
       'P', 'T', 'G', 'G', 'C', 'T', 'N', 'P', 'Y', 'G', 'K', 'S', 'K',
       'F', 'F', 'I', 'E', 'E', 'M', 'I', 'R', 'D', 'L', 'C', 'Q', 'A',
       'D', 'K', 'T', 'W', 'N', 'V', 'V', 'L', 'L', 'R', 'Y', 'F', 'N',
       'P', 'T', 'G', 'A', 'H', 'A', 'S', 'G', 'C', 'I', 'G', 'E', 'D',
       'P', 'Q', 'G', 'I', 'P', 'N', 'N', 'L', 'M', 'P', 'Y', 'V', 'S',
       'Q', 'V', 'A', 'I', 'G', 'R', 'R', 'E', 'A', 'L', 'N', 'V', 'F',
       'G', 'N', 'D', 'Y', 'D', 'T', 'E', 'D', 'G', 'T', 'G', 'V', 'R',
       'D', 'Y', 'I', 'H', 'V', 'V', 'D', 'L', 'A', 'K', 'G', 'H', 'I',
       'A', 'A', 'L', 'R', 'K', 'L', 'K', 'E', 'Q', 'C', 'G', 'C', 'R',
       'I', 'Y', 'N', 'L', 'G', 'T', 'G', 'T', 'G', 'Y', 'S', 'V', 'L',
       'Q', 'M', 'V', 'Q', 'A', 'M', 'E', 'K', 'A', 'S', 'G', 'K', 'K',
       'I', 'P', 'Y', 'K', 'V', 'V', 'A', 'R', 'R', 'E', 'G', 'D', 'V',
       'A', 'A', 'C', 'Y', 'A', 'N', 'P', 'S', 'L', 'A', 'Q', 'E', 'E',
       'L', 'G', 'W', 'T', 'A', 'A', 'L', 'G', 'L', 'D', 'R', 'M', 'C',
       'E', 'D', 'L', 'W', 'R', 'W', 'Q', 'K', 'Q', 'N', 'P', 'S', 'G',
       'F', 'G', 'T', '?'], dtype=object)

In [35]:
def construct_positional(d, m=5):
    s = m//2
    pad = ['-']*s + list(d) + ['-']*s
    n = len(d)
    rows = []
    
    for i in xrange(s, n+s):
        row = pad[i-s:i+s+1]
        rows.append(row)
    
    return rows

In [43]:
def construct_positional_header(m=5):
    s = m//2
    return ['AA'+str(i) for i in xrange(-s, s+1)]

In [44]:
construct_positional_header()

['AA-2', 'AA-1', 'AA0', 'AA1', 'AA2']

In [38]:
positional = np.asarray(construct_positional(seq))

In [42]:
print data.shape
print positional.shape

(693, 2)
(693, 5)

In [41]:
positional[:10]

array([['-', '-', 'A', 'E', 'K'],
       ['-', 'A', 'E', 'K', 'V'],
       ['A', 'E', 'K', 'V', 'L'],
       ['E', 'K', 'V', 'L', 'V'],
       ['K', 'V', 'L', 'V', 'T'],
       ['V', 'L', 'V', 'T', 'G'],
       ['L', 'V', 'T', 'G', 'G'],
       ['V', 'T', 'G', 'G', 'A'],
       ['T', 'G', 'G', 'A', 'G'],
       ['G', 'G', 'A', 'G', 'Y']],
      dtype='|S1')

In [45]:
pos_df = pd.DataFrame(positional, columns=construct_positional_header())
pos_df.head(10)

  AA-2 AA-1 AA0 AA1 AA2
0    -    -   A   E   K
1    -    A   E   K   V
2    A    E   K   V   L
3    E    K   V   L   V
4    K    V   L   V   T
5    V    L   V   T   G
6    L    V   T   G   G
7    V    T   G   G   A
8    T    G   G   A   G
9    G    G   A   G   Y

In [51]:
full_df = pos_df.join(data['SS'])

In [52]:
full_df.head(10)

  AA-2 AA-1 AA0 AA1 AA2 SS
0    -    -   A   E   K  C
1    -    A   E   K   V  C
2    A    E   K   V   L  E
3    E    K   V   L   V  E
4    K    V   L   V   T  E
5    V    L   V   T   G  E
6    L    V   T   G   G  E
7    V    T   G   G   A  T
8    T    G   G   A   G  T
9    G    G   A   G   Y  T